buddhist_exchange/urls.py
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings
from accounts.forms import UserenaSignupFormBase, SignupReaderForm
from accounts.forms import EditProfileForm
from core.views import signup as core_views_signup


from userena.views import profile_edit as userena_views_profile_edit
from userena.views import email_change as userena_views_email_change
from userena.views import password_change as userena_views_password_change
from userena.views import activate as userena_views_activate
from userena.views import email_confirm as userena_views_email_confirm
from django.conf.urls.i18n import i18n_patterns


admin.autodiscover()

urlpatterns = [
    url(r'^admin/buddhist_exchange/translator/', include('rosetta.urls')),
    url(r'^admin/', include(admin.site.urls))
]

urlpatterns += i18n_patterns(

    url(r'^accounts/signup/$', core_views_signup,
            {'signup_form': UserenaSignupFormBase, "success_url": "/?msg=signup_success"},
            name='userena_signup'),
    url(r'^accounts/signup_reader/$', core_views_signup,
            {'signup_form': SignupReaderForm, "success_url": "/?msg=signup_success", "template_name": "userena/signup_reader_form.html"},
            name='userena_signup_reader'),
    url(r'^accounts/(?P<username>[\.\w-]+)/edit/$',
       userena_views_profile_edit,
       {'edit_profile_form': EditProfileForm, 'success_url':"/account/summary"},
       name='userena_profile_edit'),
    url(r'^accounts/(?P<username>[\.\w-]+)/edit/from_view_bag$',
       userena_views_profile_edit,
       {'edit_profile_form': EditProfileForm, 'success_url':"/view_bag", 'extra_context':{'validate_receiver':True}},
       name='userena_profile_edit_from_view_bag'), #from view_bag for logged in accounts
    url(r'^accounts/(?P<username>[\.\w-]+)/edit/from_inventory$',
       userena_views_profile_edit,
       {'edit_profile_form': EditProfileForm, 'success_url':"/account/material", 'extra_context':{'validate_giver': True}},
       name='userena_profile_edit_from_inventory'), #from Book I am receiving for logged in accounts

    url(r'^accounts/(?P<username>[\.\w-]+)/email/$',
       userena_views_email_change,{'success_url':"/account/summary/?msg=email_success", "template_name": "userena/email_form.html"},
       name='userena_email_change'),

    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^accounts/', include('userena.urls')),
    url(r'^', include('core.urls')),
    url(r'^', include('timeline.urls')),
    url(r'^', include('network.urls')),
    # message app over contrib.umessage
    url(r'^message/', include('message.urls')),
    url(r'^message/', include('userena.contrib.umessages.urls')),

    url(r'^(?P<username>[\.\w-]+)/password/$',
       userena_views_password_change,{'success_url':"/account/summary/?msg=password_success", "template_name": "userena/password_form.html"},
       name='userena_password_change'),

    url(r'^activate/(?P<activation_key>\w+)/$', userena_views_activate, {'success_url':"/account/summary/?msg=activate_success"}, name='userena_activate' ),


    url(r'^confirm-email/(?P<confirmation_key>\w+)/$', userena_views_email_confirm, {'success_url':"/account/summary/?msg=email_change_success"}, name='userena_email_confirm'),


)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

core/urls.py
from django.conf.urls import include, url
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required

from .views import GiverMaterialCreateView, GiverMaterialEditView
from .views import *

def to_template(template_name):
    return TemplateView.as_view(template_name=template_name)

urlpatterns = [
    url(r'^freebook$', index, name='index'),
    url(r'^to-giver/$', to_template('to-giver.html'), name='to_giver'),
    url(r'^to-reader/$', to_template('to-reader.html'), name='to_reader'),
    url(r'^shipping/$', to_template('shipping.html'), name='shipping'),
    url(r'^help/$', to_template('help.html'), name='help'),

    url(r'^tos/$', to_template('tos.html'), name='tos'),
    url(r'^account/language-detect/$', account_language, name='account_language'),
    url(r'^account/summary/$', account_summary, name='account_summary'),
    url(r'^account/orders/reading/$', account_reading_orders, name='account_reading_orders'),
    url(r'^account/orders/giving/$', account_giving_orders, name='account_giving_orders'),
    url(r'^account/material/$', account_material, name='account_material'),
    url(r'^account/material/new/$', account_material_edit, name='account_material_new'),
    url(r'^account/giver-material/new/$', login_required(GiverMaterialCreateView.as_view()),
        name='giver_material_new'),
    url(r'^account/givermatrial/edit/(?P<pk>\d+)/$', login_required(GiverMaterialEditView.as_view()),
        name='giver_material_edit'),
    url(r'^account/material/(?P<material_id>\d+)/edit/$', account_material_edit, name='account_material_edit'),
    url(r'^account/add/publisher/$', account_add_publisher, name='account_add_publisher'),

    url(r'^account/material/new/existing/$', to_template('account/material_new_from_existing.html'),
        name='material_new_from_existing'),
    url(r'^add/(?P<model_name>\w+)/?$', add_new_model, name="add_new_model"),
    url(r'^users/(?P<username>[\w.@+-]+)/$', user_profile, name='user_profile'),
    url(r'^check_out/$', check_out, name='check_out'),
    url(r'^view_bag/$', view_bag, name='view_bag'),
    url(r'^view_bag/delete/(?P<inventory_id>\d+)/$', view_bag_delete, name='view_bag_delete'),
    url(r'^contact_user/$', contact_user, name='contact_user'),
    url(r'^pay_giver/$', pay_giver, name='pay_giver'),
    url(r'^file_claim/$', file_claim, name='file_claim'),

]

timeline/urls.py
from django.conf.urls import url
from .views import Home, ShareLink, ShareText, reblog, like_timelineitem, unlike_timelineitem,\
    TimeLineItemView, TimeLineItemComment, ShareTextUpdateView, ShareLinkUpdateView,\
    retrieve_titles, retrieve_topics, retrieve_teachers
from django.contrib.auth.decorators import login_required

urlpatterns = [
    url(r'^$', Home.as_view(), name='home'),
    url(r'^timeline/(?P<category_slug>[-\w]+)/(?P<topic_slug>[-\w]+)/$', Home.as_view(), name='item_list'),
    url(r'^timeline/(?P<category_slug>[-\w]+)/(?P<topic_slug>[-\w]+)/(?P<post_slug>[-\w]+)/$', TimeLineItemView.as_view(), name='timelineitem_detail'),
    url(r'^timeline/timelineitem/share_text$', login_required(ShareText.as_view()), name='text_form'),
    url(r'^timeline/timelineitem/share_link$', login_required(ShareLink.as_view()), name='link_form'),
    url(r'^timeline/timelineitem/(?P<timelineitem_id>\d+)/like$', like_timelineitem, name='timelineitem_like'),
    url(r'^timeline/timelineitem/(?P<timelineitem_id>\d+)/unlike$', unlike_timelineitem, name='timelineitem_unlike'),
    url(r'^timeline/timelineitem/(?P<timelineitem_id>\d+)/reblog$', reblog, name='timelineitem_reblog'),
    #url(r'^timeline/timelineitem/(?P<pk>\d+)/detail$', TimeLineItemView.as_view(), name='timelineitem_detail'),
    url(r'^timeline/timelineitem/(?P<pk>\d+)/comment$', TimeLineItemComment.as_view(), name='timelineitem_comment'),
    url(r'^timeline/timelineitem/(?P<pk>\d+)/edit/sharetext$', ShareTextUpdateView.as_view(), name='timelineitem_edit_text'),
    url(r'^timeline/timelineitem/(?P<pk>\d+)/edit/sharelink$', ShareLinkUpdateView.as_view(), name='timelineitem_edit_link'),
    url(r'^timeline/timelineitem/titles$', retrieve_titles, name='timelineitem_titles'),
    url(r'^timeline/timelineitem/teachers$', retrieve_teachers, name='timelineitem_teachers'),
    url(r'^timeline/timelineitem/topics$', retrieve_topics, name='timelineitem_topics'),

]

timeline/models.py
from django.db import models
from django.utils.translation import ugettext as _
from userena.utils import user_model_label
from .const import TEACHER_TYPE_CHOICES, TEACHER_TEACHER
import uuid

PDF_HTML_HTM_FILE_TYPES = [
    'application/pdf',
    'text/html',
    'text/htm',
]


class Language(models.Model):
    name = models.CharField(max_length=50, null=False, blank=True)
    lang_code = models.CharField(max_length=10, unique=True)
    order = models.IntegerField()
    users = models.ManyToManyField(
        user_model_label, through='UserLanguage', related_name='languages')

    class Meta:
        verbose_name = "Language"
        verbose_name_plural = "Languages"

    def __str__(self):
        return self.name


class UserLanguage(models.Model):
    user = models.ForeignKey(
        user_model_label, related_name='user_userlanguages')
    language = models.ForeignKey(
        Language, related_name='language_userlanguages')


class ItemCategoryManager(models.Manager):

    def get_all_catergories(self):
        return super(ItemCategoryManager, self).get_queryset().order_by('order')

    def get_link_form_categories(self):
        return super(ItemCategoryManager, self).filter(link_form=True).order_by('order')

    def get_text_form_categories(self):
        return super(ItemCategoryManager, self).filter(text_form=True).order_by('order')


class ItemCategory(models.Model):
    name = models.CharField(max_length=50, null=False, blank=True)
    order = models.PositiveIntegerField()
    link_form = models.BooleanField()
    text_form = models.BooleanField()
    order = models.IntegerField()
    objects = ItemCategoryManager()
    slug = models.SlugField(unique=True, max_length=225,
                            allow_unicode=True)

    class Meta:
        verbose_name = "Category"
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.name


class ItemTopic(models.Model):
    name = models.CharField(max_length=50, null=False, blank=True, unique=True)
    slug = models.SlugField(unique=True, max_length=225,
                            allow_unicode=True)

    class Meta:
        verbose_name = "Topic"
        verbose_name_plural = "Topics"

    def __str__(self):
        return self.name


class Teacher(models.Model):
    name = models.CharField(max_length=200, null=False, blank=True)
    teacher_type = models.CharField(
        max_length=200, choices=TEACHER_TYPE_CHOICES, default=TEACHER_TEACHER)

    class Meta:
        verbose_name = "Teacher"
        verbose_name_plural = "Teachers"

    def __str__(self):
        return self.name


def text_form_file_name(instance, filename):
    return '/'.join(['timeline', str(uuid.uuid4()) + '_' + filename])


class TimelineItem(models.Model):
    """
    Generic/Base model for all TimelineItem type , Article/Audio/Video etc Post , Link,
    """
    created_user = models.ForeignKey(
        user_model_label, related_name='timeline_item_creator')
    created = models.DateTimeField(_("Created Date Time"), auto_now_add=True)
    modified = models.DateTimeField(_("Modified Date Time"), auto_now=True)

    title = models.CharField(
        max_length=500, db_index=True)
    slug = models.SlugField(unique=True, max_length=225,
                            allow_unicode=True)
    title_link = models.CharField(max_length=500)
    item_category = models.ForeignKey(ItemCategory)
    content = models.TextField(blank=True, null=True)
    language = models.ForeignKey(Language)
    teacher = models.ForeignKey(Teacher, null=True)
    is_original = models.BooleanField()
    uploaded_file = models.FileField(
        upload_to=text_form_file_name, null=True, blank=True)
    file_type = models.CharField(
        max_length=50, null=False, blank=True, default='')
    file_name = models.CharField(
        max_length=50, null=False, blank=True, default='')
    topics = models.ManyToManyField(ItemTopic, related_name='timelineitems')
    users = models.ManyToManyField(
        user_model_label, related_name='user_items')
    likes = models.ManyToManyField(
        user_model_label, related_name='like_items')

    class Meta:
        verbose_name = "Post"
        verbose_name_plural = "Posts"

    def __str__(self):
        return self.title

    @property
    def total_likes(self):
        return self.likes.count()

    @property
    def content_length(self):
        return len(self.content)

    @property
    def total_reblogs(self):
        count = self.users.count()
        if count > 0:
            return self.users.count() - 1
        else:
            return 0

    @property
    def total_comments(self):
        return self.comments.count()

    def like(self, user):
        self.likes.add(user)
        self.save()

    def unlike(self, user):
        self.likes.remove(user)
        self.save()

    def is_uploaded_file_pdfhtml(self):
        if self.uploaded_file and self.file_type in PDF_HTML_HTM_FILE_TYPES:
            return True
        return False

    def is_uploaded_file_pdf(self):
        return self.file_type == 'application/pdf'

    def reblog(self, user):
        self.users.add(user)
        self.save()


class TimelineItemComment(models.Model):
    """
    Keep the comment of a timeline item
    """
    item = models.ForeignKey(TimelineItem, related_name='comments')
    comment_user = models.ForeignKey(
        user_model_label, related_name='comment_user')
    text = models.TextField()
    created = models.DateTimeField(_("Created Date Time"), auto_now_add=True)
    modified = models.DateTimeField(_("Modified Date Time"), auto_now=True)

templates/timeline/link_form.html
{% extends 'base.html' %}
{% load i18n %}
{% load readmore el_pagination_tags staticfiles %}
{% block extra_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/timeline_app.css' %}" />
	<style>

		.content-center {
		    float: left;
		    width: 100%; 
		}

			.form-group input[type="text"] ,.form-group   textarea{

			display: block;
			width: 100%;
			height: 34px;
			padding: 6px 12px;
			font-size: 14px;
			line-height: 1.42857143;
			color: #555555;
			background-color: #ffffff;
			background-image: none;
			border: 1px solid #cccccc;
			border-radius: 4px;
			-webkit-box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075);
			box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075);
			-webkit-transition: border-color ease-in-out .15s, -webkit-box-shadow ease-in-out .15s;
			-o-transition: border-color ease-in-out .15s, box-shadow ease-in-out .15s;
			transition: border-color ease-in-out .15s, box-shadow ease-in-out .15s;
 
		}
	.in-line-columns {
			 display:inline-flex !important;
			}
		@media all and (max-width : 767px) {
			.in-line-columns {
			 display:block !important;
			width:100% !important;
			}


			.new-post-form form input[type="text"] {
			    width: 100%;
			    border: 1px solid #c2b999;
			}

			.new-post-form form textarea#id_content {
			    width: 100%;
			    height: 200px;
			    font-size: 12px;
			}
		}	
	</style>
{% endblock %}


{% block subheader %}
    {% include "subheader.html"%}
{% endblock subheader %}

{% block content %}
<div class="content-center">
    <div class="new-post-form">
        {% if form.instance.pk  %}
            <form class="row" action="{% url 'timelineitem_edit_link'  form.instance.pk %}" method="post" id="new-post-form" stye="width: 900px;">
        {% else %}
            <form class="row"  action="{% url 'link_form'  %}" method="post" id="new-post-form" stye="width: 900px;">
        {% endif %}
	        {% csrf_token %}
            <div class="col-lg-6 form" style="float:left;border-right:1px dashed black; ">
                  <div class="form-group">
                    <label><b>{% trans "Basics" %}:</b></label><label>{% trans "Share Dharma teachings, resources and your own expeirences." %} </label>
		</div>
		<div class="form-group">
                    <label class="col-xs-12  col-lg-2 link-label">{% trans "Link Points to" %} : </label>
                    {% for radio in form.item_category %}
                    {{ radio.tag }} {{ radio.choice_label }}
                    {% endfor %}
                    <br>
                </div>
                  <div class="form-group">
                    <label class="col-xs-12 col-lg-2  link-label">{% trans "Title of Article/Book.." %}: </label>{{ form.title }} {{ form.title.errors }}
                </div>
                  <div class="form-group">
                    <label class="col-xs-12  col-lg-2  link-label">{% trans "Title Link" %}: </label>{{ form.title_link }} {{ form.title_link.errors }}
                </div>
                  <div class="form-group">
                    <label class="col-xs-12  col-lg-2  link-label">{% trans "Text(Optional)" %}: </label>{{ form.content }}{{ form.content.errors }}
                </div>
                  <div class="form-group">
                    <label class="col-xs-12  col-lg-2 link-label">{% trans "Language" %}:</label>{{ form.language }}{{ form.language.errors }}
                </div>
            </div>

            <div class="col-lg-6" style="float:left;">
                 <div class="form-group">
                <label class="col-xs-12 link-label"><b>{% trans "Extended" %}:</b></label>{% trans "Add additional information to give your content more exposure. All Optional." %} </div>
                 <div class="form-group">
                    <label class="col-xs-12  col-lg-2  link-label">{% trans "Teacher" %}:</label>{{ form.teacher_name }}{{ form.teacher_name.errors }}
                    </select>
                </div>
                  <div class="form-group">
                    <label class="col-xs-12  col-lg-2  link-label">{% trans "Topics" %}:</label><div class="in-line-columns">{{ form.topic_list }}, {{ form.topic_list }}, {{ form.topic_list }} </div>
                </div>
                  <div class="form-group">
                    <label class="col-xs-12   col-lg-2  link-label">{% trans "Is Original" %}:</label>
                    {{ form.is_original }}{% trans "The main content of this post is my own writing or artistic creation." %}{{ form.is_original.errors }}
                </div>
            </div>
            <div class="col-lg-6" style=" text-align:right;">
                <button class="button" style="float:none;" type="submit">{% trans "Submit" %}</button><br/>
            </div>
        </form>
    </div>
</div>


{% endblock %}
{% block extra_js %}
    {% include "timeline/timeline_post_js.html"%}
{% endblock %}

templates/timeline/text_form.html
{% extends 'base.html' %}
{% load i18n %}
{% load readmore el_pagination_tags staticfiles %}
{% block extra_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/timeline_app.css' %}" />

	<style>
		.content-center {
		    float: left;
		    width: 100%; 
		}

		.form-group input[type="text"] ,.form-group   textarea{

			display: block;
			width: 100%;
			height: 34px;
			padding: 6px 12px;
			font-size: 14px;
			line-height: 1.42857143;
			color: #555555;
			background-color: #ffffff;
			background-image: none;
			border: 1px solid #cccccc;
			border-radius: 4px;
			-webkit-box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075);
			box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075);
			-webkit-transition: border-color ease-in-out .15s, -webkit-box-shadow ease-in-out .15s;
			-o-transition: border-color ease-in-out .15s, box-shadow ease-in-out .15s;
			transition: border-color ease-in-out .15s, box-shadow ease-in-out .15s;
 
		}
	.in-line-columns {
			 display:inline-flex !important;
			}
		@media all and (max-width : 767px) {
			.in-line-columns {
			 display:block !important;
			width:100% !important;
			}


			.new-post-form form input[type="text"] {
			    width: 100%;
			    border: 1px solid #c2b999;
			}

			.new-post-form form textarea#id_content {
			    width: 100%;
			    height: 200px;
			    font-size: 12px;
			}
		}	
	</style>
{% endblock %}

{% block subheader %}
    {% include "subheader.html"%}
{% endblock subheader %}

{% block content %}
<div class="content-center">
    <div class="new-post-form">
            {% if form.instance.pk  %}
                <form class="row" action="{% url 'timelineitem_edit_text'  form.instance.pk %}" method="post" id="new-post-form" stye="width: 900px;" enctype="multipart/form-data">
            {% else %}
                <form class="row" action="{% url 'text_form'  %}" method="post" id="new-post-form" stye="width: 900px;" enctype="multipart/form-data">
            {% endif %}
            {% csrf_token %}
            <div class="col-lg-6" style="float:left;border-right:1px dashed black;">
                <div  class="form-group">
                    <label class="col-xs-12  col-lg-2  link-label"><b>{% trans "Basics" %}:</b></label>{% trans "Share Dharma teachings, resources and your own expeirences." %}</div><div  class="form-group">
                    <label class="col-xs-12  col-lg-2  link-label">{% trans "Post is" %}: </label>
                    {% for radio in form.item_category %}
                    {{ radio.tag }} {{ radio.choice_label }}
                    {% endfor %} 
                </div>
                <div class="form-group">
                    <label class="col-xs-12  col-lg-2  link-label">{% trans "Title or Quote" %}: </label>{{ form.title }}
                        {% if form.title.errors   %}
                        <label></label>{{ form.title.errors }}
                        {% endif %}
                </div>
                <div id="div_text_id" class="form-group">
                    <label class="col-xs-12  col-lg-2  link-label">{% trans "Expanded Text" %}: </label>{{ form.content }}{{ form.content.errors }}
                </div>
                <div class="form-group">
                    <label class="col-xs-12  col-lg-2  link-label">{% trans "Is Original" %}:</label>{{ form.is_original }}The main content of this post is my own writing or artistic creation.{{ form.is_original.errors }}
                    </select>
                </div>
                <div id="div_teacher_id" class="form-group">
                    <label class="col-xs-12  col-lg-2  link-label">{% trans "Teacher" %}(Optional):</label>{{ form.teacher_name }}{{ form.teacher_name.errors }}
                </div>
                <div class="form-group">
                    <label class="col-xs-12  col-lg-2  link-label">{% trans "Language" %}:</label>{{ form.language }}{{ form.language.errors }}
                </div>
            </div>
            <div  class="col-lg-6" style="float:left;">
                <label><b>{% trans "Extended" %}:</b></label>{% trans "Add additional information to give your content more exposure. All Optional." %}<br><br>
                <div class="form-group">
                    <label class="col-xs-12  col-lg-2  link-label">{% trans "Topics" %}:</label><div class="in-line-columns">{{ form.topic_list }}, {{ form.topic_list }}, {{ form.topic_list }} {{ form.topic_list.errors }}</div>
                <div class="form-group">
                    <label class="col-xs-12  col-lg-2  link-label">{% trans "Upload a Picture/HTML/PDF" %}: </label>
                    {% if form.instance.pk and form.instance.uploaded_file  %}
                    <a href="{{ form.instance.uploaded_file.url }}">{{ form.instance.file_name }}</a>
                    {% endif %}
                    {{ form.uploaded_file }}{{ form.uploaded_file.errors }}
                </div>
            </div>
            <div class="col-lg-6" style=" text-align:right;">
                <button class="button" style="float:none;" type="submit">{% trans "Submit" %}</button>
            </div>
        </form>
    </div>
</div>

{% endblock %}
{% block extra_js %}
{% include "timeline/timeline_post_js.html"%}
<script type="text/javascript">
$(function() {

    toggleTextContent();
    toggleTeacherName();

    $("input[name='item_category']").click(function(){
        toggleTextContent()
    });

    $('#id_is_original').click(function() {
        toggleTeacherName()
    });

});
function toggleTextContent(){
    if($('input:radio[name=item_category]:checked').val() == "2"){
        $('#div_text_id').hide();
        $('#id_content').val('');
    }else{
        $('#div_text_id').show();
    }
}

function toggleTeacherName(){
    if ($('#id_is_original').is(':checked')) {
        $('#div_teacher_id').hide();
        $('#id_teacher_name').val('');
    }else{
        $('#div_teacher_id').show();
    }
}
</script>
{% endblock %}

templates/timeline/timeline_js.html
<script type="text/javascript">
	$(function() {
		var item_language = "{{ search_language.lang_code }}";
		var item_usertype = "{{ request.GET.usertype }}";
		if (item_language !== '' &&  item_language !== null) {
			$("#item_language option[value='" + item_language + "']").attr("selected", "selected");
		}
		if (item_usertype !== '' &&  item_usertype !== null) {
			$("#item_usertype option[value='" + item_usertype + "']").attr("selected", "selected");
		}
	});

	function showSelected() {
		var item_language = $("#item_language option:selected").val();
		var item_usertype = $("#item_usertype option:selected").val();
		var item_category = "{{ category_slug }}";
		var item_topic = "{{ topic_slug }}";
		var current_lang_code = "{{ LANGUAGE_CODE }}"

		url = "{% url 'item_list' category_slug  topic_slug %}"
		if ( item_usertype ){
			url = url + '?usertype=' + item_usertype
		}
		window.location = url.replace(current_lang_code,item_language);
	}


	function reblog(id) {
		$.ajax({
			type: "POST",
			data: {
				'csrfmiddlewaretoken': '{{ csrf_token }}'
			},
			dataType: "json",
			url: $('#reblog_' + id).attr("href"),
			success: function(response) {
				$('#reblog_count_' + id).html(response.reblog_count);
			}
		});
		return false
	};

	function like(id) {
		$.ajax({
			type: "POST",
			data: {
				'csrfmiddlewaretoken': '{{ csrf_token }}'
			},
			dataType: "json",
			url: $('#like_' + id).attr("href"),
			success: function(response) {
				$('#unlike_count_' + id).html(response.likes_count);
				$('#like_' + id).hide();
				$('#unlike_' + id).show();
			}
		});
		return false
	};

	function unlike(id) {
		$.ajax({
			type: "POST",
			data: {
				'csrfmiddlewaretoken': '{{ csrf_token }}'
			},
			dataType: "json",
			url: $('#unlike_' + id).attr("href"),
			success: function(response) {
				$('#like_count_' + id).html(response.likes_count);
				$('#like_' + id).show();
				$('#unlike_' + id).hide();
			}
		});
		return false
	};
</script>

templates/timeline/timeline_post_js.html
<script type="text/javascript">
$(function() {
    var topiclist ={{form.existing_topic|safe}};
    $('input[name="topic_list"]').each( function( index, element ){
        if(topiclist.length >= index){
            $( this ).val(topiclist[index]);
        }
    });

    $("#id_title").autocomplete({
        minLength: 5,
        source: function (request, response) {
             $.ajax({
                 url: "{% url 'timelineitem_titles' %}",
                 type: "GET",
                 data: {title: request.term},
                 success: function (data) {
                     response(data.titles);
                 }
             });
         }
    });

    $("#id_teacher_name").autocomplete({
        source: function (request, response) {
             $.ajax({
                 url: "{% url 'timelineitem_teachers' %}",
                 type: "GET",
                 data: {teacher: request.term},
                 success: function (data) {
                     response(data.teachers);
                 }
             });
         }
    });

    $( "input[name='topic_list']" ).each( function( index, element ){
        $(this).autocomplete({
            source: function (request, response) {
                 $.ajax({
                     url: "{% url 'timelineitem_topics' %}",
                     type: "GET",
                     data: {topic: request.term},
                     success: function (data) {
                         response(data.topics);
                     }
                 });
             }
        });
 });
 });
 </script>