buddhist_exchange/urls.py
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings
from accounts.forms import UserenaSignupFormBase, SignupReaderForm
from accounts.forms import EditProfileForm
from core.views import signup as core_views_signup


from userena.views import profile_edit as userena_views_profile_edit
from userena.views import email_change as userena_views_email_change
from userena.views import password_change as userena_views_password_change
from userena.views import activate as userena_views_activate
from userena.views import email_confirm as userena_views_email_confirm
from django.conf.urls.i18n import i18n_patterns


admin.autodiscover()

urlpatterns = [
    url(r'^admin/buddhist_exchange/translator/', include('rosetta.urls')),
    url(r'^admin/', include(admin.site.urls))
]

urlpatterns += i18n_patterns(

    url(r'^accounts/signup/$', core_views_signup,
            {'signup_form': UserenaSignupFormBase, "success_url": "/?msg=signup_success"},
            name='userena_signup'),
    url(r'^accounts/signup_reader/$', core_views_signup,
            {'signup_form': SignupReaderForm, "success_url": "/?msg=signup_success", "template_name": "userena/signup_reader_form.html"},
            name='userena_signup_reader'),
    url(r'^accounts/(?P<username>[\.\w-]+)/edit/$',
       userena_views_profile_edit,
       {'edit_profile_form': EditProfileForm, 'success_url':"/account/summary"},
       name='userena_profile_edit'),
    url(r'^accounts/(?P<username>[\.\w-]+)/edit/from_view_bag$',
       userena_views_profile_edit,
       {'edit_profile_form': EditProfileForm, 'success_url':"/view_bag", 'extra_context':{'validate_receiver':True}},
       name='userena_profile_edit_from_view_bag'), #from view_bag for logged in accounts
    url(r'^accounts/(?P<username>[\.\w-]+)/edit/from_inventory$',
       userena_views_profile_edit,
       {'edit_profile_form': EditProfileForm, 'success_url':"/account/material", 'extra_context':{'validate_giver': True}},
       name='userena_profile_edit_from_inventory'), #from Book I am receiving for logged in accounts

    url(r'^accounts/(?P<username>[\.\w-]+)/email/$',
       userena_views_email_change,{'success_url':"/account/summary/?msg=email_success", "template_name": "userena/email_form.html"},
       name='userena_email_change'),

    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^accounts/', include('userena.urls')),
    url(r'^', include('core.urls')),
    url(r'^', include('timeline.urls')),
    url(r'^', include('network.urls')),
    # message app over contrib.umessage
    url(r'^message/', include('message.urls')),
    url(r'^message/', include('userena.contrib.umessages.urls')),

    url(r'^(?P<username>[\.\w-]+)/password/$',
       userena_views_password_change,{'success_url':"/account/summary/?msg=password_success", "template_name": "userena/password_form.html"},
       name='userena_password_change'),

    url(r'^activate/(?P<activation_key>\w+)/$', userena_views_activate, {'success_url':"/account/summary/?msg=activate_success"}, name='userena_activate' ),


    url(r'^confirm-email/(?P<confirmation_key>\w+)/$', userena_views_email_confirm, {'success_url':"/account/summary/?msg=email_change_success"}, name='userena_email_confirm'),


)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

core/urls.py
from django.conf.urls import include, url
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required

from .views import GiverMaterialCreateView, GiverMaterialEditView
from .views import *

def to_template(template_name):
    return TemplateView.as_view(template_name=template_name)

urlpatterns = [
    url(r'^freebook$', index, name='index'),
    url(r'^to-giver/$', to_template('to-giver.html'), name='to_giver'),
    url(r'^to-reader/$', to_template('to-reader.html'), name='to_reader'),
    url(r'^shipping/$', to_template('shipping.html'), name='shipping'),
    url(r'^help/$', to_template('help.html'), name='help'),

    url(r'^tos/$', to_template('tos.html'), name='tos'),
    url(r'^account/language-detect/$', account_language, name='account_language'),
    url(r'^account/summary/$', account_summary, name='account_summary'),
    url(r'^account/orders/reading/$', account_reading_orders, name='account_reading_orders'),
    url(r'^account/orders/giving/$', account_giving_orders, name='account_giving_orders'),
    url(r'^account/material/$', account_material, name='account_material'),
    url(r'^account/material/new/$', account_material_edit, name='account_material_new'),
    url(r'^account/giver-material/new/$', login_required(GiverMaterialCreateView.as_view()),
        name='giver_material_new'),
    url(r'^account/givermatrial/edit/(?P<pk>\d+)/$', login_required(GiverMaterialEditView.as_view()),
        name='giver_material_edit'),
    url(r'^account/material/(?P<material_id>\d+)/edit/$', account_material_edit, name='account_material_edit'),
    url(r'^account/add/publisher/$', account_add_publisher, name='account_add_publisher'),

    url(r'^account/material/new/existing/$', to_template('account/material_new_from_existing.html'),
        name='material_new_from_existing'),
    url(r'^add/(?P<model_name>\w+)/?$', add_new_model, name="add_new_model"),
    url(r'^users/(?P<username>[\w.@+-]+)/$', user_profile, name='user_profile'),
    url(r'^check_out/$', check_out, name='check_out'),
    url(r'^view_bag/$', view_bag, name='view_bag'),
    url(r'^view_bag/delete/(?P<inventory_id>\d+)/$', view_bag_delete, name='view_bag_delete'),
    url(r'^contact_user/$', contact_user, name='contact_user'),
    url(r'^pay_giver/$', pay_giver, name='pay_giver'),
    url(r'^file_claim/$', file_claim, name='file_claim'),

]

accounts/forms.py
import time
from django import forms
from django.db import IntegrityError
from django.utils.text import slugify
from userena.forms import SignupForm as UserenaSignupForm
from userena.forms import EditProfileForm as UserenaEditProfileForm
from accounts.models import Profile
from django_countries import countries
from core.models import Order, GiverMaterial
from timeline.models import Language, UserLanguage

USERNAME_RE = r'^[\.\w]+$'


NUM_CHOICES = (
    ('0', 'Unlimitted'), #nobody will choose 0 for this, so it means unlimitted.
    ('1', '1'),
    ('3', '3'),
    ('5', '5'),
    ('10', '10'),
    ('20', '20'),
    ('30', '30'),
    ('40', '40'),
    ('50', '50'),
)

BOOL_CHOICES = (
    (True, True),
    (False, False),
)

STATE_CHOICES = (
    ("", "----------"),
    ("AL", "Alabama"),
    ("AK","Alaska"),
    ("AS","American Samoa"),
    ("AZ","Arizona"),
    ("AR","Arkansas"),
    ("AA","Armed Forces Americas"),
    ("AE","Armed Forces Europe"),
    ("AP","Armed Forces Pacific"),
    ("CA","California"),
    ("CO","Colorado"),
    ("CT","Connecticut"),
    ("DE","Delaware"),
    ("DC","District of Columbia"),
    ("FM","Federated States of Micronesia"),
    ("FL","Florida"),
    ("GA","Georgia"),
    ("GU","Guam"),
    ("HI","Hawaii"),
    ("ID","Idaho"),
    ("IL","Illinois"),
    ("IN","Indiana"),
    ("IA","Iowa"),
    ("KS","Kansas"),
    ("KY","Kentucky"),
    ("LA","Louisiana"),
    ("ME","Maine"),
    ("MH","Marshall Islands"),
    ("MD","Maryland"),
    ("MA","MA"),
    ("MI","Michigan"),
    ("MN","Minnesota"),
    ("MS","Mississippi"),
    ("MO","Missouri"),
    ("MT","Montana"),
    ("NE","Nebraska"),
    ("NV","Nevada"),
    ("NH","New Hampshire"),
    ("NJ","New Jersey"),
    ("NM","New Mexico"),
    ("NY","New York"),
    ("NC","North Carolina"),
    ("ND","North Dakota"),
    ("MP","Northern Mariana Islands"),
    ("OH","Ohio"),
    ("OK","Oklahoma"),
    ("OR","Oregon"),
    ("PW","Palau"),
    ("PA","Pennsylvania"),
    ("PR","Puerto Rico"),
    ("RI","Rhode Island"),
    ("SC","South Carolina"),
    ("SD","South Dakota"),
    ("TN","Tennessee"),
    ("TX","Texas"),
    ("UM","U.S. Minor Outlying Islands"),
    ("UT","Utah"),
    ("VT","Vermont"),
    ("VI","Virgin Islands"),
    ("VA","Virginia"),
    ("WA","Washington"),
    ("WV","West Virginia"),
    ("WI","Wisconsin"),
    ("WY","Wyoming"),

)

class LanguageFormMixin(forms.Form):
    language = forms.ModelChoiceField(
        queryset=None, empty_label='--Choose One--', required=False)
    language1 = forms.ModelChoiceField(
        queryset=None, empty_label='--Choose One--', required=False)
    language2 = forms.ModelChoiceField(
        queryset=None, empty_label='--Choose One--', required=False)
    language3 = forms.ModelChoiceField(
        queryset=None, empty_label='--Choose One--', required=False)

    def __init__(self, *args, **kwargs):
        super(LanguageFormMixin, self).__init__(*args, **kwargs)
        queryset = Language.objects.all().order_by('order')
        self.fields['language'].queryset = queryset
        self.fields['language1'].queryset = queryset
        self.fields['language2'].queryset = queryset
        self.fields['language3'].queryset = queryset

    def save_userlanguage(self, user):
        languages = [self.cleaned_data['language'], self.cleaned_data[
            'language1'], self.cleaned_data['language2'], self.cleaned_data['language3']]
        for language in languages:
            if language and user:
                ul, created = UserLanguage.objects.get_or_create(
                    user=user, language=language)

    def update_userlanguage(self, user):
        UserLanguage.objects.all().filter(user=self.instance.user).delete()
        self.save_userlanguage(user)


attrs_dict = {'class': 'required'}
class UserenaSignupFormBase(LanguageFormMixin, UserenaSignupForm):
    def __init__(self, *args, **kwargs):
        super(UserenaSignupFormBase, self).__init__(*args, **kwargs)
        self.fields['country'].initial = "US"

    """ Add a Terms of Service button to the ``SignupForm``. """
    tos = forms.BooleanField(widget=forms.CheckboxInput(attrs=attrs_dict), \
                             label='I have read and agree to the Terms of Service', \
                             error_messages={'required': 'You must agree to the terms to register.'})
    #username = forms.CharField(required=True, widget=forms.TextInput(attrs={'placeholder':'Your real name or nick name.'}))

    us_state = forms.ChoiceField(choices = STATE_CHOICES, required = False)
    state = forms.CharField(max_length = 50)

    country = forms.ChoiceField(choices = list(countries), initial="US", required = True)

    def save(self):
        user = super(UserenaSignupFormBase, self).save()
        profile = user.profile
        profile.state = self.cleaned_data['state']
        profile.country = self.cleaned_data['country']
        profile.save()
        self.save_userlanguage(user)
        return user


class SignupReaderForm(UserenaSignupFormBase):
    first_name = forms.CharField()
    last_name = forms.CharField()
    address1 = forms.CharField(max_length=255)
    address2 = forms.CharField(max_length=255, required = False)
    city = forms.CharField(max_length=50)
    zipcode = forms.CharField(max_length=50)

    def __init__(self, *args, **kwargs):
        super(SignupReaderForm, self).__init__(*args, **kwargs)

    def save(self):
        user = super(SignupReaderForm, self).save()
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.save()

        profile = user.profile
        profile.address1 = self.cleaned_data['address1']
        profile.address2 = self.cleaned_data['address2']
        profile.city = self.cleaned_data['city']
        #profile.is_reader = True
        profile.zipcode = self.cleaned_data['zipcode']
        profile.save()
        return user
"""
class SignupForm(UserenaSignupFormBase):
    first_name = forms.CharField(required=False) #first name/last name not required
    last_name = forms.CharField(required=False)
    screen_name = forms.CharField(widget=forms.TextInput(attrs={'placeholder':'Your real name or nick name.'}))
    paypal_email = forms.EmailField(required=False)
    other_means = forms.CharField(widget=forms.Textarea(attrs={'placeholder': 'Ask users to mail you a check, provide instruction and mailing address here. '}), required=False)
    free_domestic_shipping = forms.ChoiceField(widget=forms.CheckboxInput, required=False, choices=BOOL_CHOICES)
    free_international_shipping = forms.ChoiceField(widget=forms.CheckboxInput, required=False, choices=BOOL_CHOICES)
    max_number_per_order = forms.ChoiceField(choices=NUM_CHOICES, initial='5')

    def __init__(self, *args, **kwargs):
        super(SignupForm, self).__init__(*args, **kwargs)

    def clean_free_domestic_shipping(self):
        return True if self.cleaned_data['free_domestic_shipping']=='True' else False

    def clean_free_international_shipping(self):
        return True if self.cleaned_data['free_international_shipping']=='True' else False

    def clean(self):
        data = self.cleaned_data
        paypal_email = data.get('paypal_email', '')
        other_means = data.get('other_means', '')
        if not paypal_email and not other_means:
            raise forms.ValidationError("Please enter either paypal_email or other means to pay, so buyers can pay you. If all your items are always free, then declare so in other payment methods field.")
        return data

    def save(self):
        user = super(SignupForm, self).save()
        user.save()

        profile = user.profile
        profile.screen_name = self.cleaned_data['screen_name']
        profile.paypal_email = self.cleaned_data['paypal_email']
        profile.description = self.cleaned_data['other_means']
        profile.domestic_free_shipping = self.cleaned_data['free_domestic_shipping']
        profile.international_free_shipping = self.cleaned_data['free_international_shipping']
        profile.max_per_order = self.cleaned_data['max_number_per_order']
        profile.status = 'REG'
        profile.state = self.cleaned_data['state']
        profile.country = self.cleaned_data['country']
        #profile.is_giver = True

        profile.save()
        return user
"""

from userena import settings as userena_settings
from userena.models import UserenaSignup
from userena.utils import get_profile_model, get_user_model

class EditProfileForm(LanguageFormMixin, UserenaEditProfileForm):
    max_per_order = forms.ChoiceField(choices = NUM_CHOICES, initial='5')
    us_state = forms.ChoiceField(choices = STATE_CHOICES, required=False)
    username = forms.RegexField(regex=USERNAME_RE,
                                max_length=30,
                                widget=forms.TextInput(attrs=attrs_dict),
                                error_messages={'invalid': 'Username must contain only letters, numbers, dots and underscores.'})


    #validate_receiver = forms.CharField()
    check_receiver = forms.BooleanField()
    check_giver  = forms.BooleanField()

    def __init__(self, *args, **kwargs):
        if len(args)>0:
            self.validate_receiver = args[0].get('validate_receiver', False)
            self.validate_giver =  args[0].get('validate_giver', False)

        super(EditProfileForm, self).__init__(*args, **kwargs)
        self.fields['username'].initial = self.instance.user.username
        self.fields['first_name'].initial = self.instance.user.first_name
        self.fields['last_name'].initial = self.instance.user.last_name
        user_langs = UserLanguage.objects.all().filter(user=self.instance.user)
        i = 0

templates/userena/email_form.html
{% extends 'account/summary.html' %}
{% load i18n %}
{#% load url %#}

{% block title %}{% trans "Account setup" %}{% endblock %}

{% block content_title %}<h2>{% blocktrans with profile.userget_profile.get_display_name as username %}Account &raquo; {{ username }}{% endblocktrans %}</h2>{% endblock %}

{% block account_right %}

<form action="" method="post">
  {% csrf_token %}

    {{ form.as_p }}

  <input type="submit" value="{% trans "Change email" %}" />
</form>
{% endblock %}

templates/userena/password_form.html
{% extends 'account/summary.html' %}
{% load i18n %}
{#% load url %#}

{% block title %}{% trans "Account setup" %}{% endblock %}

{% block content_title %}<h2>{% blocktrans with profile.userget_profile.get_display_name as username %}Account &raquo; {{ username }}{% endblocktrans %}</h2>{% endblock %}

{% block account_right %}
<form action="" method="post" id="password_change_form">


    {% csrf_token %}
    {{ form.as_p }}

  <input type="submit" value="{% trans "Change password" %}" />
</form>
{% endblock %}

templates/userena/password_reset_form.html
{% extends 'userena/base_userena.html' %}
{% load i18n %}

{% block title %}{% trans "Reset password" %}{% endblock %}

{% block content %}

<div class="box" style="width:300px;margin:0 auto;">

	<div class="header">{% trans "Reset Password" %}</div>
	<div class="box-content">

	<form action="" method="post">

	    {% csrf_token %}
	    {{ form.as_p }}

	  <input type="submit" value="{% trans "Send password" %}" />
	</form>
	</div>
	<br><br>
</div>
{% endblock %}

templates/userena/profile_detail.html
{% extends 'account/summary.html' %}
{% load i18n %}
{#% load url %#}

{% block title %}{% blocktrans with profile.user.username as username %}{{ username }}'s profile.{% endblocktrans %}{% endblock %}
{% block content_title %}<h2>{{ profile.user.username }} {% if profile.user.get_full_name %}({{ profile.user.get_full_name }}){% endif %}</h2>{% endblock %}

{% block account_right %}
  <div class="white-box">
    {% block profile_navigation %}
      {% comment %}Dirty hack. Will use django-guardian in the future.{% endcomment %}
      {% if user.username == profile.user.username %}
        <ul id="box-nav">
          {% block profile_navigation_items %}
            <li><a href="{% url 'userena_profile_detail' user.username %}">{% trans "View profile" %}</a></li>
            <li><a href="{% url 'userena_profile_edit' user.username %}">{% trans "Edit details" %}</a></li>
            <li><a href="{% url 'userena_password_change' user.username %}">{% trans "Change password" %}</a></li>
            <li><a href="{% url 'userena_email_change' user.username %}">{% trans "Change email" %}</a></li>
          {% endblock %}
        </ul>
      {% endif %}
    {% endblock %}

    <div id="details">
      {% block profile_details %}
        <img class="mugshot" src="{{ profile.get_mugshot_url }}" alt="{% trans "Your mugshot" %}" />
        <dl>
          {% block profile_definition_list %}
            {% if profile.user.get_full_name %}
              <dt>{% trans "Name" %}</dt>
              <dd>{{ profile.user.get_full_name }}</dd>
            {% endif %}
            {% if profile.user.email and not hide_email %}
              <dt>{% trans "Email" %}</dt>
              <dd>{{ profile.user.email }}</dd>
            {% endif %}
            {% if profile.age %}
              <dt>{% trans "Age" %}</dt>
              <dd>{{ profile.age }}</dd>
            {% endif %}
            {% if profile.website %}
              <dt>{% trans "Website" %}</dt>
              <dd>{{ profile.website|urlize }}</dd>
            {% endif %}
            {% if profile.location %}
              <dt>{% trans "Location" %}</dt>
              <dd>{{ profile.location }}</dd>
            {% endif %}
            {% if profile.about_me %}
              <dt>{% trans "About me" %}</dt>
              <dd>{{ profile.about_me }}</dd>
            {% endif %}
          {% endblock %}
        </dl>
      {% endblock %}
    </div>
  </div>
{% endblock %}

templates/userena/profile_form.html
{% extends 'account/summary.html' %}
{% load i18n %}
{#% load url %#}

{% block title %}{% trans "Account setup" %}
<style>
input[type='checkbox'] {width: 30px; height: 30px;}
</style>
{% endblock %}

{% block content_title %}<h2>{% blocktrans with profile.userget_profile.get_display_name as username %}Account &raquo; {{ username }}{% endblocktrans %}</h2>{% endblock %}



{% block account_right %}

{% if form.errors %}
<!-- div id="form-error">
	<p>The operation could not be performed because one or more error(s) occurred.<br />Please resubmit the form after making the following changes:</p>
	<ul>
	{% for field in form %}
	<li>{{field.label}}  - {{ field.errors|striptags }}</li>
	{% endfor %}
	</ul>
</div-->
{% endif %}



<form action="" enctype="multipart/form-data" method="post">
  <!--  ul id="box-nav">
    <li class="first"><a href="{% url 'userena_profile_detail' user.username %}"><span>{% trans 'View profile' %}</span></a></li>
    <li class="selected"><a href="{% url 'userena_profile_edit' user.username %}">{% trans "Edit profile" %}</a></li>
    <li><a href="{% url 'userena_password_change' user.username %}">{% trans "Change password" %}</a></li>
    <li class="last"><a href="{% url 'userena_email_change' user.username %}">{% trans "Change email" %}</a></li>
  </ul -->
  {% csrf_token %}

    <h2>{% trans "Update Profile" %}:</h2>

	{% if form.non_field_errors %}
	<ul class="errorlist">
	    {% for non_field_error in form.non_field_errors %}
	        <li>{{ non_field_error }}</li>
	    {% endfor %}
	</ul>
	{% endif %}

    <input type="hidden" name="validate_receiver" value="{{validate_receiver}}">
    <input type="hidden" name="validate_giver" value="{{validate_giver}}">

    <h3>{% trans "Section 1. Membership Information" %}:  </h3>
    <div class="form-group"><label>{% trans "User Name" %}:</label>{{ form.username }}{{ form.username.errors }}  </div>
    <div class="form-group"><label>{% trans "Country" %}:</label>{{ form.country }}{{ form.country.errors }}</div>
    <div class="form-group"><label>{% trans "State" %}:</label>{{ form.us_state }}{{form.state}}{{form.state.errors}}</div>
    <div class="form-group"><label>{% trans "Language" %}:</label>{{ form.language }}{{ form.language.errors}} {{ form.language1 }}{{ form.language1.errors}} {{ form.language2 }}{{ form.language2.errors}} {{ form.language3}}{{ form.language3.errors}}</div>


    <!-- div><label>Show my public profile:</label>{{ form.is_public }}{{ form.is_public.errors }} * Complete public profile to let users know more about you.</div-->

    <h3 style="font-size: 13px;">{% trans "Section 2." %} <input type="checkbox" name="check_receiver" id="id_check_receiver" {% if validate_receiver or user.profile.has_reader_profile %} checked {% endif %}>
    {% trans "Receiver - Mailing Information" %}:</h3>
    <div class="form-group"><label>{% trans "First Name" %}:</label>{{ form.first_name }}{{ form.first_name.errors }}</div>
    <div class="form-group"><label>{% trans "Last Name" %}:</label>{{ form.last_name }}{{ form.last_name.errors }}</div>
    <div class="form-group"><label>{% trans "Address 1" %}:</label>{{ form.address1 }}{{ form.address1.errors }}</div>
    <div class="form-group"><label>{% trans "Address 2" %}:</label>{{ form.address2 }}{{ form.address2.errors }}</div>
    <div class="form-group"><label>{% trans "City" %}:</label>{{ form.city }}{{ form.city.errors }}</div>
    <div class="form-group"><label>{% trans "Zip Code" %}:</label>{{ form.zipcode }}{{ form.zipcode.errors }}</div>

    <h3>{% trans "Section 3" %}. </br> <input type="checkbox" name="check_giver" id="id_check_giver" {% if validate_giver or user.profile.has_giver_profile %} checked {% endif %}>Giver - Distribution Information:</h3></br>

	<div class="form-group" style="font-size: 13px;"><label>{% trans "Distribution Methods" %}:</label></br><label> </label>{{ form.local_pickup }} {% trans "Local Pickup: Receiver picks up books from your location." %} <br>
	<label> </label>{{ form.domestic_free_shipping }} Free Domestic Shipping: Sender covers domestic shipping expenses. <br>
	<label> </label>{{ form.domestic_pay_shipping }} Receive Payment for Domestic Shipping: Receiver pays shipping expenses upfront.  <br>
	<label> </label>{{ form.international_free_shipping }} Free International Shipping: Sender covers international shipping expenses.
	<label></label>{{ form.free_domestic_shipping.errors }} {{ form.free_international_shipping.errors }}
	</div>
    <div class="form-group"><label>{% trans "How to Pickup Locally" %}:</label>{{ form.pickup_description }}{{ form.pickup_description.errors }}</div>

    <div class="form-group"><label>{% trans "Max Free Items Per shipment" %}:</label>{{ form.max_per_order }}{{ form.max_per_order.errors }} *{% trans "Receiver is required to contact sender if ordering more than this number of free books." %}</div>
    <div class="form-group"><label>{% trans "How to Donate/How is receipt returned" %}:</label>{{ form.donation }}{{ form.donation.errors }}</div>
    <br>
    <div class="form-group"><label></label>{% trans "Payment methods" %}:</div>

    <div class="form-group"><label>{% trans "Paypal Email" %}:</label>{{ form.paypal_email }}{{ form.paypal_email.errors }}</div>
    <div class="form-group"><label>{% trans "Online Payment Url" %}:</label>{{ form.pay_url }}{{ form.pay_url.errors }}</div>
    <div class="form-group"><label>{% trans "Online Donation Url" %}:</label>{{ form.donate_url }}{{ form.donate_url.errors }}</div>
    <div class="form-group"><label>{% trans "Other payment methods" %}:</label>{{ form.payment_description }}{{ form.payment_description.errors }}</div>
    <div class="form-group" style="font-size: 13px;"><label>{% trans "Use for Donation" %}:</label>{{ form.payinfo_for_donation }}{% trans "Use above payment methods for donation." %}</div>

    <!--  >Section 4. Public Profile - Information required for displaying your profile to public:</h3>
    <div><label>Entity Type:</label>{{ form.type }}{{ form.type.errors }}</div>
    <div><label>Is Non-profit:</label>{{ form.is_nonprofit }}{{ form.is_nonprofit.errors }} * Whether donation to you is tax deductible.</div>
    <div><label>Your Profile Picture:</label>{{ form.mugshot }}{{ form.mugshot.errors }}</div>
    <div><label>Your Website:</label>{{ form.website }}{{ form.website.errors }}</div>
    <div><label>Your Facebook page:</label>{{ form.facebook }}{{ form.facebook.errors }}</div>
    <div><label>The Bodhi path of your organization or yourself:</label>{{ form.description }}{{ form.description.errors }}</div-->


  <input type="submit" class="btn" value="{% trans "Save changes" %}" />
</form>

<script>
$(document).ready(function(){ 
	$("input[type=text], input[type=email],input[type=url],select,textarea  ").attr("class","form-control");
	$("input[type=checkbox]").css("width","30px");
	$("input[type=checkbox]").css("height","30px");
});
</script>
<script language ="javascript">
$(function() {
	countryStateInit();
});
</script>
{% endblock %}

templates/userena/signup_complete.html
{% extends 'base.html' %}
{% load i18n %}
{% block content %}

<h2>Register</h2>
	{% trans "Thanks for registering! Please check for the welcome email and follow the instruction to login." %}

{% endblock %}